# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Create Pre-Release

on: workflow_dispatch

env:
  BUILD_VERSION:  ${{ secrets.SEMANTIC_VERSION }}
  CONFIGURATION: "Release"
  PUBLISH_FOLDER: "./publish/"
  PUBLISH_FDD_ZIP: "EdFi.AnalyticsMiddleTier.zip"
  PUBLISH_SCD_ZIP: "EdFi.AnalyticsMiddleTier-win10.x64.zip"

jobs:
  AMT-Create-Release:
    runs-on: Ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Caching packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
   
      - name: Publish self-contained deployment
        run: |
          .\build.ps1 publish -SelfContained ${{ env.CONFIGURATION }} -Version ${{ env.BUILD_VERSION }} -BuildCounter ${{ github.run_number }}
        shell: pwsh

      - name: Publish framework-dependent deployment
        run: |
          .\build.ps1 publish -Configuration ${{ env.CONFIGURATION }} -Version ${{ env.BUILD_VERSION }} -BuildCounter ${{ github.run_number }}
        shell: pwsh

      - name: Create Zip file
        run: |
          .\build.ps1 CreateZip -Configuration ${{ env.CONFIGURATION }} -Version ${{ env.BUILD_VERSION }} -BuildCounter ${{ github.run_number }}
        shell: pwsh

      - name: Create pre-release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.BUILD_VERSION }}-pre${{ github.run_id }}
          release_name: ${{ env.BUILD_VERSION }} <Release name> 
          body: |
            <Release description>
          draft: false
          prerelease: true

      - name: Upload publish zip
        id: upload-publish-zip-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ env.PUBLISH_FOLDER }}${{ env.PUBLISH_FDD_ZIP }}
          asset_name: ${{ env.PUBLISH_FDD_ZIP }}
          asset_content_type: application/zip

      - name: Upload self-contained publish zip
        id: upload-publish-self-contained-zip-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ env.PUBLISH_FOLDER }}${{ env.PUBLISH_SCD_ZIP }}
          asset_name: ${{ env.PUBLISH_SCD_ZIP }}
          asset_content_type: application/zip